{% set name = "pbsv" %}
{% set version = "2.2.2" %}
{% set sha256 = "d530db8890f4cf28708f9803661d04e669f4d5b69f28b3bf0ca2b5a1d2e22952" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/PacificBiosciences/pbsv/releases/download/v{{ version }}/pbsv
  sha256: {{ sha256 }}

build:
  number: 1
  skip: True  # [osx]

test:
  commands:
    - pbsv -h

about:
  home: https://github.com/PacificBiosciences/pbbioconda
  license: BSD-3-Clause-Clear
  summary: "pbsv - PacBio structural variant (SV) calling and analysis tools"

extra:
  recipe-maintainers:
    - armintoepfer
    - pb-dseifert
    - mhsieh
  skip-lints:
    #repackaged binary
    - should_be_noarch_generic
