{% set name = "isoseq3" %}
{% set version = "3.1.2" %}
{% set sha256 = "4fb8a5601c6403b0441b9247f4a642374fc3d50e72ed207052be4fc629bea168" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/PacificBiosciences/IsoSeq3/releases/download/v{{ version }}/isoseq3
  sha256: {{ sha256 }}

about:
  home: https://github.com/PacificBiosciences/pbbioconda
  license: BSD-3-Clause-Clear
  summary: IsoSeq3 - Scalable De Novo Isoform Discovery

extra:
  recipe-maintainers:
    - armintoepfer
    - pb-dseifert
    - mhsieh

build:
  number: 0
  skip: True # [osx]

requirements:
  run:
    - lima
    - pbccs
    - pbcoretools

test:
  commands:
    - isoseq3 -h
