{% set name = "isoseq3" %}
{% set version = "3.2.1" %}
{% set sha256 = "62f2ad2d600a7bfafd9f13b30654d74681b32b904feea514922afd521201c428" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/PacificBiosciences/IsoSeq3/releases/download/v{{ version }}/isoseq3
  sha256: {{ sha256 }}

build:
  number: 2
  skip: True  # [osx]

test:
  commands:
    - isoseq3 -h

about:
  home: https://github.com/PacificBiosciences/pbbioconda
  license: BSD-3-Clause-Clear
  summary: IsoSeq3 - Scalable De Novo Isoform Discovery

extra:
  recipe-maintainers:
    - armintoepfer
    - pb-dseifert
    - mhsieh
  skip-lints:
    #repackaged binary
    - should_be_noarch_generic
