{% set name = "pbmm2" %}
{% set version = "0.10.1" %}
{% set sha256 = "f75ca6ed448cf52310b91cfdc7b26db48c1b4d4875e00bd82c100a4964394e56" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/PacificBiosciences/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

about:
  home: https://github.com/PacificBiosciences/pbmm2
  license: BSD-3-Clause-Clear
  summary: A minimap2 frontend for PacBio native data formats

extra:
  recipe-maintainers:
    - armintoepfer
    - pb-dseifert
    - mhsieh

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - meson ==0.46.0*
    - ninja
    - pkg-config
  host:
    - boost
    - zlib
    - pbbam 0.19.0*
    - pbcopper 0.4.2*
  run:
    - pbbam 0.19.0*
    - pbcopper 0.4.2*

test:
  commands:
    - pbmm2 -h
